-- AlterTable
ALTER TABLE "ApiKey" ADD COLUMN "currentHourUsage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "hourlyResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "currentDayUsage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "dailyResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
